apiVersion: v1
kind: Pod
metadata:
  name: nginx-rouge
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: nginx-rouge
    image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "red"
